language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
  - SYMFONY_CONSOLE_VERSION=~2.3.6
  - SYMFONY_CONSOLE_VERSION=2.4.*
  - SYMFONY_CONSOLE_VERSION=2.5.*

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
    - composer require --no-update --prefer-source --dev symfony/http-kernel:${SYMFONY_CONSOLE_VERSION}
    - composer require --no-update --prefer-source --dev symfony/console:${SYMFONY_CONSOLE_VERSION}
    - composer require --no-update --prefer-source --dev symfony/config:${SYMFONY_CONSOLE_VERSION}
    - composer require --no-update --prefer-source --dev symfony/dependency-injection:${SYMFONY_CONSOLE_VERSION}
    - composer install

script:
    - bin/atoum
